Paymill:
  secret_key: 'PAYMILL_SECRET_KEY'
  public_key: 'PAYMILL_PUBLIC_KEY'

Twitter:
  consumer_key: 'TWITTER_CONSUMER_KEY'
  consumer_secret: 'TWITTER_CONSUMER_SECRET'
  token: 'TWITTER_TOKEN'
  token_secret: 'TWITTER_TOKEN_SECRET'

Cloudinary:
  cloud_name: 'CLOUDINARY_CLOUD_NAME'
  preset: 'CLOUDINARY_PRESET'
  api_key: 'CLOUDINARY_API_KEY'
  api_secret: 'CLOUDINARY_API_SECRET'
